export type SampleMenuItem = {
  title: string
  href: string
}

export const samplesTitle = 'Samples'
export const samplesIntro = 'Bộ sưu tập các component/demo dùng trong dự án.'

export const sampleMenuItems: SampleMenuItem[] = [
  { title: 'Alert', href: '/samples/alert' },
  { title: 'Button', href: '/samples/button' },
  { title: 'Card', href: '/samples/card' },
  { title: 'FileCard', href: '/samples/filecard' },
  { title: 'FileList', href: '/samples/filelist' },
  { title: 'Table', href: '/samples/table' },
  { title: 'Offcanvas', href: '/samples/offcanvas' },
  { title: 'StorageUsage', href: '/samples/storageusage' },
  { title: 'Navbar', href: '/samples/navbar' },
  { title: 'Dialog', href: '/samples/dialog' },
  { title: 'Loading', href: '/samples/loading' },
  { title: 'FormCard', href: '/samples/formcard' },
  { title: 'FormGroup', href: '/samples/formgroup' },
  { title: 'FormInput', href: '/samples/formgroup/forminput' },
  { title: 'FormSelect', href: '/samples/formgroup/formselect' },
  { title: 'FormTextarea', href: '/samples/formgroup/formtextarea' },
  { title: 'FormCheckbox', href: '/samples/formgroup/formcheckbox' },
  { title: 'FormRadio', href: '/samples/formgroup/formradio' },
  { title: 'FormSwitch', href: '/samples/formgroup/formswitch' },
  { title: 'FormUpload', href: '/samples/formgroup/formupload' },
  { title: 'NavGroup', href: '/samples/navgroup' },
  { title: 'Subnav', href: '/samples/subnav' },
  { title: 'Breadcrumb', href: '/samples/breadcrumb' },
  { title: 'File upload test', href: '/samples/test-page/file-upload-test' },
  { title: 'Move file test', href: '/samples/test-page/move-file-test' },
  { title: 'List files test', href: '/samples/test-page/list-files-test' },
  { title: 'File detail test', href: '/samples/test-page/file-detail-test' },
  { title: 'File download test', href: '/samples/test-page/file-download-test' },
  { title: 'File update test', href: '/samples/test-page/file-update-test' },
  { title: 'File delete test', href: '/samples/test-page/file-delete-test' },
  { title: 'File copy test', href: '/samples/test-page/file-copy-test' },
  { title: 'Admin file version delete test', href: '/samples/test-page/file-version-delete-test' },
  { title: 'Recent files test', href: '/samples/test-page/recent-files-test' },
  { title: 'File preview test', href: '/samples/test-page/file-preview-test' },
  { title: 'Create folder test', href: '/samples/test-page/create-folder-test' },
  { title: 'Move folder test', href: '/samples/test-page/move-folder-test' },
  { title: 'Folder tree test', href: '/samples/test-page/folder-tree-test' },
  { title: 'Folder breadcrumb test', href: '/samples/test-page/folder-breadcrumb-test' },
  { title: 'List folders test', href: '/samples/test-page/list-folders-test' },
  { title: 'Folder detail test', href: '/samples/test-page/folder-detail-test' },
  { title: 'Folder contents test', href: '/samples/test-page/folder-contents-test' },
  { title: 'Folder rename test', href: '/samples/test-page/folder-rename-test' },
  { title: 'Folder delete test', href: '/samples/test-page/folder-delete-test' },
  { title: 'Folder copy test', href: '/samples/test-page/folder-copy-test' },
  { title: 'Bulk copy test', href: '/samples/test-page/bulk-copy-test' },
  { title: 'Bulk delete test', href: '/samples/test-page/bulk-delete-test' },
  { title: 'Bulk move test', href: '/samples/test-page/bulk-move-test' },
  { title: 'Dashboard overview test', href: '/samples/test-page/dashboard-test' },
  { title: 'Dashboard stats test', href: '/samples/test-page/dashboard-stats-test' },
  { title: 'File version upload test', href: '/samples/test-page/file-version-test' },
  { title: 'File version list test', href: '/samples/test-page/file-version-list-test' },
  { title: 'File version detail test', href: '/samples/test-page/file-version-detail-test' },
  { title: 'File version download test', href: '/samples/test-page/file-version-download-test' },
  { title: 'File version restore test', href: '/samples/test-page/file-version-restore-test' },
  { title: 'Public link create test', href: '/samples/test-page/public-link-create-test' },
  { title: 'Public link list test', href: '/samples/test-page/public-link-list-test' },
  { title: 'Public link detail test', href: '/samples/test-page/public-link-detail-test' },
  { title: 'Public link update test', href: '/samples/test-page/public-link-update-test' },
  { title: 'Public link preview test', href: '/samples/test-page/public-link-preview-test' },
  { title: 'Public link download test', href: '/samples/test-page/public-link-download-test' },
  { title: 'Public link revoke test', href: '/samples/test-page/public-link-revoke-test' },
  { title: 'File public links test', href: '/samples/test-page/file-public-links-test' },
  { title: 'Global search test', href: '/samples/test-page/global-search-test' },
  { title: 'Search suggestions test', href: '/samples/test-page/search-suggestions-test' },
  { title: 'Share create test', href: '/samples/test-page/share-create-test' },
  { title: 'Share list test', href: '/samples/test-page/share-list-test' },
  { title: 'Share detail test', href: '/samples/test-page/share-detail-test' },
  { title: 'Share delete test', href: '/samples/test-page/share-delete-test' },
  { title: 'Received share list test', href: '/samples/test-page/share-received-list-test' },
  { title: 'Share remove user test', href: '/samples/test-page/share-remove-user-test' },
  { title: 'Storage breakdown test', href: '/samples/test-page/storage-breakdown-test' },
  { title: 'Storage limit test', href: '/samples/test-page/storage-limit-test' },
  { title: 'Trash list test', href: '/samples/test-page/trash-list-test' },
  { title: 'Trash folder contents test', href: '/samples/test-page/trash-folder-contents-test' },
  { title: 'Trash restore test', href: '/samples/test-page/trash-restore-test' },
  { title: 'Trash delete test', href: '/samples/test-page/trash-delete-test' },
  { title: 'Trash empty test', href: '/samples/test-page/trash-empty-test' },
  { title: 'Admin configs test', href: '/samples/test-page/admin-configs-test' },
  { title: 'Admin config detail test', href: '/samples/test-page/admin-config-detail-test' },
  { title: 'Admin config update test', href: '/samples/test-page/admin-config-update-test' },
  { title: 'Admin dashboard test', href: '/samples/test-page/admin-dashboard-test' },
  { title: 'Admin user stats test', href: '/samples/test-page/admin-stats-users-test' },
  { title: 'Admin file stats test', href: '/samples/test-page/admin-stats-files-test' },
  { title: 'Admin storage stats test', href: '/samples/test-page/admin-stats-storage-test' },
  { title: 'Admin storage overview test', href: '/samples/test-page/admin-storage-overview-test' },
  { title: 'Admin storage users test', href: '/samples/test-page/admin-storage-users-test' },
  { title: 'Admin users test', href: '/samples/test-page/admin-users-test' },
  { title: 'Admin user detail test', href: '/samples/test-page/admin-user-detail-test' },
  { title: 'Admin user create test', href: '/samples/test-page/admin-user-create-test' },
  { title: 'Admin user delete test', href: '/samples/test-page/admin-user-delete-test' },
  { title: 'Admin user update test', href: '/samples/test-page/admin-user-update-test' },
  { title: 'Admin user storage usage test', href: '/samples/test-page/admin-user-storage-usage-test' },
  { title: 'Admin user role update test', href: '/samples/test-page/admin-user-role-update-test' },
]


